### ISSUE TITLE
current temperature shows invalid temp

### ISSUE THREAD

**Issue by sbushnell** [turmoni/ooler-mqtt-bridge#4] opened 2022-11-11 18:31 UTC
All is working well except current temperature shows a minus value which does change as temp changes... Desired temperature 
 16 is correct. 
When the current temp is 16 it shows -9

![screenshot 96](https://user-images.githubusercontent.com/5581790/201405942-7ec8b788-5517-4566-a843-fc283ed1f1f4.jpg)

**Comment by sbushnell** [comment] 2022-11-11 18:54
Update. when the current temp is 16 it shows -9

**Comment by docBliny** [comment] 2022-12-11 00:52
Looks like the current temperature is wrong when you've set the device display temperature to Celsius in the app. I added logic to fetch the display unit to my local copy and that seems to work. Will need to try to find the time to create a PR with that and some other changes/fixes.

**Comment by turmoni** [comment] 2022-12-12 01:07
Weird! I have the app set to Celsius and (obviously) don't have this problem. What platforms are you both using for the app/how long have you had an Ooler? I wonder if there's either some alternative platform stuff going on (I use Android), or some historical setting that I've avoided running into.

Before @docBliny 's comment I was also going to ask whether this was on the main branch or the Bleak one, but wasn't expecting too much to come out of the answer to that.

**Comment by docBliny** [comment] 2022-12-12 01:18
I'm on iOS. There are two separate options for the temperature. One is for device units and the other for "App Unit Preference".

My rough patches:

constants.py:
```python
DISPLAY_TEMPERATURE_UNIT = "2c988613-fe15-4067-85bc-8e59d5e0b1e3"

class TemperatureUnit(Enum):
    Fahrenheit = 0
    Celsius = 1
```

and then I added the following (and some other) code to get things going, but I'd need to clean it up some for a PR:
```python
from ooler.constants import TemperatureUnit
#...

    def __init__(self, address=None, stay_connected=True, max_connection_attempts=5):
        self.address = address
        self.current_temperature_unit = None
#....

    @property
    def temperature_unit(self) -> TemperatureUnit:
        """Return the temperature unit of the Ooler"""
        unit = self._request_characteristic(constants.DISPLAY_TEMPERATURE_UNIT)
        self.current_temperature_unit = TemperatureUnit(
            int.from_bytes(unit, byteorder="big"))
        return self.current_temperature_unit

    @temperature_unit.setter
    def temperature_unit(self, unit: TemperatureUnit) -> None:
        """Return the temperature unit of the Ooler"""
        self._write_characteristic(
            constants.DISPLAY_TEMPERATURE_UNIT, unit.value.to_bytes(1, byteorder="big")
        )

        # Cache optimistically
        self.current_temperature_unit = unit

    def get_actual_temperature(self, unit: TemperatureUnit) -> int:
        """Get the current temperature in the requested units"""
        temperature = int.from_bytes(
            self._request_characteristic(constants.ACTUAL_TEMP), byteorder="big"
        )
        # Make sure we have the current temperature units
        if self.current_temperature_unit is None:
            self.current_temperature_unit = self.temperature_unit

        if self.current_temperature_unit == unit:
            # Requested units and current units match, return as-is
            return temperature
        elif unit == TemperatureUnit.Celsius:
            return self._f_to_c(temperature)
        else:
            return self._c_to_f(temperature)

    @property
    def actual_temperature_f(self) -> int:
        """Get the current temperature in Fahrenheit"""
        return self.get_actual_temperature(TemperatureUnit.Fahrenheit)

    @property
    def actual_temperature_c(self) -> int:
        """Get the current temperature in Celsius"""
        return self.get_actual_temperature(TemperatureUnit.Celsius)
```

It looks like the desired temperature still always needs to be set in Fahrenheit.

**Comment by turmoni** [comment] 2022-12-12 01:27
Well today I learned - thanks, I had managed to miss that option. I'll play with that tomorrow, it's well past my bedtime today.

**Comment by sbushnell** [comment] 2022-12-12 04:26
Hi, Thanks for the update!Excellent utility!! I'm on Android and have it
integrated with OpenHab.. and yes my app is set to Celsius.

Will wait patiently for the PR :-)

Cheers
Scott

**Comment by turmoni** [comment] 2022-12-15 13:27
Well, on Android, at least, it looks like I can't switch the device units from F to C unless it's actively on (the setting changes in the UI but isn't actually saved), but now I've managed to switch it (which is good for me), and to reproduce the issue, so I'll quickly add something based on @docBliny's comment to make it work properly

**Comment by turmoni** [comment] 2022-12-15 13:50
I've done a slightly simpler change that doesn't allow for setting the device units via the library, let me know if it works

**Comment by sbushnell** [comment] 2022-12-15 19:21
Thanks for the update. Works perfectly :-)

**Comment by turmoni** [comment] 2023-01-15 22:47
Closing now that I've also fixed this for the Bleak branch

**Closed as completed by turmoni** 2023-01-15 22:47 UTC
